# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-03 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2016, 9, 3, 9, 14, 54, 855564, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
