# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 9, 4, 4, 55, 30, 711382, tzinfo=utc), max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
