# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 26, 18, 17, 25, 286752, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
